In [2]:
# Numpy python lib use for numerical computing . allows us to work with arrays instead of python lists more efficent
# handle multidimensional arrays , perform mathematical operations on arrays easily 
import numpy as np


In [3]:
array1 = np.array([1,2,3,4,5])

In [5]:
type(array1)

numpy.ndarray

In [7]:
array2 = np.array([
    [1,2,3,4,5],
    [6,7,8,8,9]
])

In [11]:
array2.shape



(2, 5)

In [13]:
array2.size

10

In [15]:
array2.ndim

2

In [17]:
array2.dtype

dtype('int64')

In [9]:
array3 = np.array([
    [
        [1,2,3],[4,5,6],[6,7,8]
    ],
     [
        [11,22,3],[4,54,64],[64,72,82]
     ]        
    ])

In [10]:
array3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 6,  7,  8]],

       [[11, 22,  3],
        [ 4, 54, 64],
        [64, 72, 82]]])

In [16]:
array4 = np.zeros((2,3,4))

In [17]:
array4


array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [22]:
arr5= np.ones((2,3,4))

In [23]:
arr5

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [30]:
np.arange(1,12)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
# linspace(start,stop,no. of steps you want to show)

In [41]:
arr6 = np.linspace(1,10,4)

In [42]:
arr6

array([ 1.,  4.,  7., 10.])

In [43]:
arr5.ndim

3

In [44]:
arr5.shape

(2, 3, 4)

In [45]:
arr5.size

24

In [46]:
arr5.dtype

dtype('float64')

In [47]:
list1 = [1,2,3,4]

In [48]:
arrList = np.array(list1)

In [50]:
print(arrList)

[1 2 3 4]


In [62]:
print(arrList*2)

[2 4 6 8]


In [63]:
array3

array([[[  2,   4,   6],
        [  8,  10,  12],
        [ 12,  14,  16]],

       [[ 22,  44,   6],
        [  8, 108, 128],
        [128, 144, 164]]])

In [64]:
array3 = array3*2

In [65]:
array3

array([[[  4,   8,  12],
        [ 16,  20,  24],
        [ 24,  28,  32]],

       [[ 44,  88,  12],
        [ 16, 216, 256],
        [256, 288, 328]]])

In [66]:
array3[1][1]

array([ 16, 216, 256])

In [18]:
# Practice

In [19]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [25]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [21]:
np.full((2,3),7)

array([[7, 7, 7],
       [7, 7, 7]])

In [27]:
np.arange(0,10,2) # just like range in python start stop and steps

array([0, 2, 4, 6, 8])

In [32]:
np.linspace(0,5,5)

array([0.  , 1.25, 2.5 , 3.75, 5.  ])

In [33]:
np.eye(3) # identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [39]:
np.random.rand(2,3) # row , col here no's b/w 0 and 1 if want specific use below one

array([[0.47371005, 0.62711178, 0.16372192],
       [0.44144265, 0.09653629, 0.35848548]])

In [41]:
np.random.randint(0,10,(2,3)) # no from o to 9 and row = 2 and col = 3

array([[6, 0, 7],
       [7, 3, 6]])

In [42]:
a = np.array([1,2,3])
b = np.array([3,4,5])
print( a+b)

[4 6 8]


In [44]:
print(a-b)

[-2 -2 -2]


In [45]:
print(a*b)

[ 3  8 15]


In [46]:
# universal functions 

In [47]:
np.sin(a)

array([0.84147098, 0.90929743, 0.14112001])

In [48]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 ])

In [49]:
np.exp(a)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [50]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081])