In [1]:
import numpy as np

In [5]:
arr1 = np.array([1,2,3])

In [6]:
arr2 = np.array([
    [2,3,4],[3,4,6],[7,8,9]
])

In [10]:
arr3 = arr1 * arr2

In [12]:
print(arr3)

[[ 2  6 12]
 [ 3  8 18]
 [ 7 16 27]]


In [15]:
Sum = np.sum(arr3)

In [16]:
print(Sum)

99


In [17]:
arr4 = np.zeros((3,4))

In [18]:
print(arr4)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [19]:
arr4[1][3] = 15

In [20]:
print(arr4)

[[ 0.  0.  0.  0.]
 [ 0.  0.  0. 15.]
 [ 0.  0.  0.  0.]]


In [21]:
print(np.sum(arr4))

15.0


In [26]:
print(np.prod(arr4))

0.0


In [27]:
arr5 = np.ones((3,4))

In [29]:
print(arr5)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [50]:
list2 = ["king","ring",1,2,3,"rose",1e3]

In [31]:
arr5 = np.array(list2)

In [32]:
arr5

array(['king', 'ring', '1', '2', '3', 'rose'], dtype='<U21')

In [33]:
arr5[3]

np.str_('2')

In [36]:
arr5[3]*4 # as its a string so cannot multiply

'2222'

In [37]:
# as in the array we do have string values so we cannot type cast them instead we can use try except

In [53]:
try:
    ind = int(input("Enter Index"))
    try:
        value = int(arr5[ind])
        print(value)
        print(type(value))
    except ValueError:
        value = arr5[ind]
        print(value,"This is value error" )
        pass
except IndexError:
    print("Enter correct index")
    

Enter Index 3


2
<class 'int'>


In [54]:
list2

['king', 'ring', 1, 2, 3, 'rose', 1000.0]

In [51]:
nums = []
for i in list2:   
    try:
        nums.append(float(i))
    except:
        pass




In [52]:
nums

[1.0, 2.0, 3.0, 1000.0]

In [55]:
# if don't want to print exponential

In [62]:
arr6 = np.array([1,2,3,4,5,6,7,8,9,22,33,55,22,66,43,54])


In [63]:
arr6.size

16

In [65]:
arr6.reshape(4,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 22, 33, 55],
       [22, 66, 43, 54]])

In [66]:
arr6.reshape(2,4,2)

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8]],

       [[ 9, 22],
        [33, 55],
        [22, 66],
        [43, 54]]])

In [67]:
arr6.reshape(2,2,2,2)

array([[[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]]],


       [[[ 9, 22],
         [33, 55]],

        [[22, 66],
         [43, 54]]]])

In [68]:
arr7 = np.array([1,2,3,4,5,6,7,8])

In [69]:
arr7.size

8

In [75]:
# np.resize = return the new array everytime but in arr.resize it changes in place in the memory and it is changed forever and it only changes orignal array
# arr1 = np.resize(arrname,(row,col))
# arr = np.array([1,2,3])
# arr.resize(row,col)
# np.resize repeat data at the end doesnot add the 0's at the end as the arr.resize do
a1 = np.resize(arr7,(3,3))

In [76]:
a1

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3]])

In [77]:
np.resize(a1,(3,4))


array([[1, 2, 3, 4],
       [5, 6, 1, 2],
       [3, 1, 2, 3]])

In [78]:
arr8 = np.array([1,2,3,4,5,6])

In [79]:
arr8.resize(3,3)

In [80]:
arr8

array([[1, 2, 3],
       [4, 5, 6],
       [0, 0, 0]])

In [83]:
np.max(arr8)

np.int64(6)

In [84]:
arr3

array([[ 2,  6, 12],
       [ 3,  8, 18],
       [ 7, 16, 27]])

In [82]:
np.max(arr3)

np.int64(27)

In [87]:
np.max(arr3,axis = 1)

array([12, 18, 27])

In [88]:
np.max(arr3)

np.int64(27)

In [90]:
expenses = np.array(
    [
        [130,240,200,180,320], # food
        [100,200,49,80,90]  , # travel
        [1000,300,320,800,900] # shopping
        
        
    ]
)



In [97]:
print("Total expense",np.sum(expenses))
print("Category wise expense",np.sum(expenses,axis = 1))
print("day wise total",np.sum(expenses,axis = 0))
print("highest expense day",np.max(np.sum(expenses,axis = 0)))

Total expense 4909
Category wise expense [1070  519 3320]
day wise total [1230  740  569 1060 1310]
highest expense day 1310


In [108]:
marks = np.array([30,10,90,78,56,45])
grade = np.where(marks >= 75, "A", 
         np.where(marks >= 55, "B", 
         np.where(marks >= 40, "C", "F")))

In [109]:
grade

array(['F', 'F', 'A', 'A', 'B', 'C'], dtype='<U1')

In [110]:
np.mean(marks)

np.float64(51.5)

In [111]:
np.std(marks)

np.float64(27.17688969204043)

In [112]:
np.median(marks)

np.float64(50.5)

In [116]:
arr = np.array([1,2,3,4])

In [117]:
%timeit arr*2

716 ns ± 12.7 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [118]:
np.split(arr,2)

[array([1, 2]), array([3, 4])]